Merge d3 into master (#21)
* draw line chart function with d3 library (#5)

* draw line chart function with d3 library

* Remove comments

* Add more styling to line charts (#6)

* added tick formatting
* add dots for smaller datasets
* zero-index the y-axis. I find this gives a better sense of scale.

* Use d3 for group bar chart (#7)

* Use d3 for group bar chart

demo link: https://screenshot.googleplex.com/jEek0HQ2Ga4

* Remove comment

* Remove unused functions; Use new legend creation for line chart (#9)

demo: https://screenshot.googleplex.com/UnqD8sJbFpm

* Use d3 for stack bar chart (#12)

* Use d3 for stack bar chart; Update getColorFn take the domain list

demo: https://screenshot.googleplex.com/EOnWvXYhEF3

* Update

* Use d3 for single bar chart (#13)

demo: https://screenshot.googleplex.com/6XcyoEtz9Rp

* Chart styling updates (#14)

- Update axes styles to follow the line chart styling
- Add padding before the left hand bar charts (paddingOuter)
- Update chart colors to use [Spectral](https://github.com/d3/d3-scale-chromatic#schemeSpectral)

Remove red borders around charts since they're not click targets

* Wrap long tick labels (#17)

* Wrap long x-axis tick text
* Removed unused code and fix typescript warnings.

* Comment out broken test for now
  TypeError: tspan.node(...).getComputedTextLength is not a function

Co-authored-by: Bo Xu <shifucun@users.noreply.github.com>